# Generated by Django 4.1.6 on 2023-06-18 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasks",
            options={"ordering": ["priority"]},
        ),
    ]
